# Force Cargo to use compatible configuration for Solana builds
# Prevents lockfile v4 generation and ensures compatibility

[build]
# Use stable Rust toolchain from system
rustc = "rustc"

[term]
verbose = false
