use anchor_lang::prelude::*;

/// Per-token statistics tracking
///
/// Each token in the ecosystem has its own TokenStats account
/// to track individual metrics like burns, fees, and cycles.
#[account]
pub struct TokenStats {
    /// The token mint this stats account tracks
    pub mint: Pubkey,

    /// Total tokens burned for this specific token
    pub total_burned: u64,

    /// Total SOL collected/generated by this token
    pub total_sol_collected: u64,

    /// Total SOL actually used for buybacks
    pub total_sol_used: u64,

    /// SOL sent to root token (if secondary)
    pub total_sol_sent_to_root: u64,

    /// SOL received from other tokens (if root)
    pub total_sol_received_from_others: u64,

    /// Number of buyback cycles for this token
    pub total_buybacks: u64,

    /// Last cycle execution timestamp
    pub last_cycle_timestamp: i64,

    /// SOL collected in last cycle
    pub last_cycle_sol: u64,

    /// Tokens burned in last cycle
    pub last_cycle_burned: u64,

    /// Whether this is the root token (receives 44.8% from all secondaries)
    pub is_root_token: bool,

    /// PDA bump seed
    pub bump: u8,

    // Per-token fee tracking for multi-token ecosystems

    /// Accumulated fees not yet collected (daemon tracks attribution)
    pub pending_fees_lamports: u64,

    /// Timestamp of last fee update
    pub last_fee_update_timestamp: i64,

    /// Number of ecosystem cycles this token participated in
    pub cycles_participated: u64,
}

impl TokenStats {
    /// Account size: Pubkey(32) + 12 u64/i64 fields (96) + bool(1) + u8(1) = 130 bytes
    pub const LEN: usize = 32 + 8 * 12 + 1 + 1;
}
